# python-chromedriver镜像包，包含python3.9以及chromedriver
image: joyzoursky/python-chromedriver:latest

stages:
  - build
  - login
  - test_cases
  - deploy

before_script:
  - python --version
  - df -h
  - echo $(date +%F%n%T)
  # 使用 https://pypi.tuna.tsinghua.edu.cn/simple 源以下载更快
  - pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
  # 将nameserver改为内网环境来访问管理平台
  - echo "nameserver  10.2.166.106" > /etc/resolv.conf
  - echo "Automated test starting..."

# 登录页自动化测试用例
job_login_page:
  stage: login
  script:
    - pytest "Test/TestCase/test_login.py" --alluredir=Report/report
  only:
    - master
  retry: 2
  # 在Gitlab运行时需要加下面的tag才能被捕捉到
  tags:
    - smc-check

# 定投管理页-新闻定投自动化测试用例
job_scheduled_pushing_page_news:
  stage: test_cases
  script:
    - pytest "Test/TestCase/test_scheduled_pushing.py::TestNewsScheduledPushing" --alluredir=Report/report
  only:
    - master
  retry: 2
  tags:
    - smc-check

# 定投管理页-音频定投自动化测试用例
job_scheduled_pushing_page_audio:
  stage: test_cases
  script:
    - pytest "Test/TestCase/test_scheduled_pushing.py::TestAudioScheduledPushing" --alluredir=Report/report
  only:
    - master
  retry: 2
  tags:
    - smc-check

# 集纳页自动化测试用例
job_jina_page:
  stage: test_cases
  script:
    - pytest "Test/TestCase/test_jina.py" --alluredir=Report/report
  only:
    - master
  retry: 2
  tags:
    - smc-check

# 24小时feed版页-"纯文字"自动化测试用例
# job_hot_24_feed_page_text:
#   stage: test_cases
#   script:
#     - pytest "Test/TestCase/test_hot_24_feed.py::TestTextHot24Feed" --alluredir=Report/report
#   only:
#     - master
#   retry: 2
#   tags:
#     - smc-check

# 24小时feed版页-"文字+图片"自动化测试用例
# job_hot_24_feed_page_pic:
#   stage: test_cases
#   script:
#     - pytest "Test/TestCase/test_hot_24_feed.py::TestPicHot24Feed" --alluredir=Report/report
#   only:
#     - master
#   retry: 2
#   tags:
#     - smc-check

# 24小时feed版页-"文字+视频"自动化测试用例
# job_hot_24_feed_page_video:
#   stage: test_cases
#   script:
#     - pytest "Test/TestCase/test_hot_24_feed.py::TestVideoHot24Feed" --alluredir=Report/report
#   only:
#     - master
#   retry: 2
#   tags:
#     - smc-check

# 24小时feed版页-"真人播报"自动化测试用例
# job_hot_24_feed_page_listen:
#   stage: test_cases
#   script:
#     - pytest "Test/TestCase/test_hot_24_feed.py::TestListenHot24Feed" --alluredir=Report/report
#   only:
#     - master
#   retry: 2
#   tags:
#     - smc-check
