# python-chromedriver source for this test, including python and chrome driver.
image: joyzoursky/python-chromedriver:latest

stages:
  - build
  - test
  - deploy

before_script:
  - python --version
  # use https://pypi.tuna.tsinghua.edu.cn/simple for quicker downloading.
  - pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
  # change nameserver to intranet environment for successfully login operation.
  - echo "nameserver  10.2.166.106" > /etc/resolv.conf
  - echo "Automated test starting..."

job_login:
  script:
    - pytest --alluredir=Report/report
  only:
    - master
  # need to add tags when running script.
  tags:
    - smc-runner
