image: python:3.10.4

stages:
  - build
  - test
  - fail
  - success
  - deploy

before_script:
  - python --version
  - pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
  - echo "Automated test starting..."

job_login:
  script:
    - pytest --alluredir=Report/report
  only:
    - master
  tags:
    - smc-runner

job_fail:
  script:
    - echo "Automated test failed."
  when: on_failure

job_success:
  script:
    - echo "Automated test finished."
  when: on_success
