image: python:3.10.4

stages:
  - build
  - test
  - fail
  - success
  - deploy

before_script:
  - python --version
  - pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
  - apt-get update && apt-get install -y gnupg2
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - curl -sS -o - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
  - apt install -y ./google-chrome-stable_current_amd64.deb
  - apt-get install -yqq unzip curl
  - wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
  - unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
  - echo "Automated test starting..."

job_login:
  services:
    - name: selenium/standalone-chrome:latest
  script:
    - pytest --alluredir=Report/report
  only:
    - master
  tags:
    - smc-runner

job_fail:
  script:
    - echo "Automated test failed."
  when: on_failure

job_success:
  script:
    - echo "Automated test finished."
  when: on_success
