websites:
  host: "opt.mrd.sohuno.com"
  loginPage: "https://sso.sohu-inc.com/login?service=http://opt.mrd.sohuno.com:10510/testhotred/ssoValidate?returnUrl=/"

loginInfo:
  username: guangyang219579
  password: Liam0829!@#$
