websites:
  host: "uattest.mrd.sohuno.com"
  loginPage: "https://sso.sohu-inc.com/login?service=http://uattest.mrd.sohuno.com/mrd-operation/ssoValidate?returnUrl=/"

loginInfo:
  username: autotestsup
  password: Autotest!@3
